-- Database schema for kohaprofile

DROP TABLE IF EXISTS datapoints;
DROP TABLE IF EXISTS commits;
DROP TABLE IF EXISTS runs;

CREATE TABLE commits (
    sha   CHAR(40) NOT NULL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE runs (
    id      INTEGER AUTO_INCREMENT PRIMARY KEY,
    started TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    branch  VARCHAR(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE datapoints (
    id        INTEGER AUTO_INCREMENT PRIMARY KEY,
    run_id    INTEGER NOT NULL,
    sha       CHAR(40) NOT NULL,
    sha_order INTEGER NOT NULL,
    name      VARCHAR(128) NOT NULL,
    method    VARCHAR(128) NOT NULL,
    value     FLOAT NOT NULL,
    created   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT runs_fk_1 FOREIGN KEY (run_id) REFERENCES runs    (id)  ON DELETE CASCADE,
    CONSTRAINT runs_fk_2 FOREIGN KEY (sha)    REFERENCES commits (sha) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
